"use client";

import { useEffect, useRef, useState } from "react";

let initialized = false;
const MERMAID_CONFIG_VERSION = 2; // bump to force re-init after config changes
let initializedVersion = 0;

interface MermaidProps {
  /** Must be unique across all rendered diagrams on the page. */
  id: string;
  chart: string;
}

/**
 * Client-only Mermaid diagram renderer.
 * Dynamically imports mermaid to keep it out of the SSR bundle.
 * The SVG output is generated from our own hardcoded diagram definitions,
 * so dangerouslySetInnerHTML is safe here.
 */
export default function Mermaid({ id, chart }: MermaidProps) {
  const [svg, setSvg] = useState<string>("");
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState<string>("");
  // track the last rendered chart to avoid stale re-renders
  const lastChart = useRef<string>("");

  useEffect(() => {
    if (lastChart.current === chart) return;

    let cancelled = false;
    setSvg("");
    setLoading(true);
    setError("");
    lastChart.current = chart;

    (async () => {
      try {
        const mermaid = (await import("mermaid")).default;

        if (!initialized || initializedVersion !== MERMAID_CONFIG_VERSION) {
          mermaid.initialize({
            startOnLoad: false,
            theme: "dark",
            darkMode: true,
            fontSize: 16,
            themeVariables: {
              background: "#030712",
              primaryColor: "#1e3a8a",
              primaryTextColor: "#e2e8f0",
              primaryBorderColor: "#3b82f6",
              lineColor: "#4b5563",
              secondaryColor: "#111827",
              tertiaryColor: "#0f172a",
              edgeLabelBackground: "#1f2937",
              clusterBkg: "#111827",
              titleColor: "#93c5fd",
              nodeBorder: "#3b82f6",
              mainBkg: "#1e293b",
              nodeTextColor: "#e2e8f0",
            },
          });
          initialized = true;
          initializedVersion = MERMAID_CONFIG_VERSION;
        }

        const elementId = `mermaid-${id}-${Date.now()}`;
        const result = await mermaid.render(elementId, chart);
        if (!cancelled) {
          setSvg(result.svg);
          setLoading(false);
        }
      } catch (err) {
        if (!cancelled) {
          setError(err instanceof Error ? err.message : String(err));
          setLoading(false);
        }
      }
    })();

    return () => {
      cancelled = true;
      lastChart.current = ""; // allow strict-mode remount to re-render
    };
  }, [id, chart]);

  if (loading) {
    return (
      <div className="flex items-center justify-center p-10 text-gray-500 text-sm">
        <span className="animate-pulse">Rendering diagram…</span>
      </div>
    );
  }

  if (error) {
    return (
      <div className="p-4 rounded-lg bg-red-950/40 border border-red-800/50 text-red-400 text-xs font-mono whitespace-pre-wrap">
        {error}
      </div>
    );
  }

  return (
    // SVG is generated by Mermaid from our own hardcoded strings — not user input
    // eslint-disable-next-line react/no-danger
    <div
      className="mermaid-output overflow-auto [&_svg]:min-w-[600px] [&_svg]:h-auto"
      dangerouslySetInnerHTML={{ __html: svg }}
    />
  );
}
